//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Purpose - Data provided via an objection
 * 			
 * 
 * &lt;p&gt;Java class for CATSObjectionData complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="CATSObjectionData"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="InitiatingRequestID" type="{urn:aseXML:r38}CATSRequestIdentifier"/&amp;gt;
 *         &amp;lt;element name="Role" type="{urn:aseXML:r38}RoleIdentifier"/&amp;gt;
 *         &amp;lt;element name="ObjectionCode" type="{urn:aseXML:r38}CATSObjectionCode"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CATSObjectionData", propOrder = {
    "initiatingRequestID",
    "role",
    "objectionCode"
})
@XmlSeeAlso({
    CATSObjectionRequest.class
})
public class CATSObjectionData {

    @XmlElement(name = "InitiatingRequestID")
    @XmlSchemaType(name = "positiveInteger")
    protected long initiatingRequestID;
    @XmlElement(name = "Role", required = true)
    protected String role;
    @XmlElement(name = "ObjectionCode", required = true)
    protected String objectionCode;

    /**
     * Gets the value of the initiatingRequestID property.
     * 
     */
    public long getInitiatingRequestID() {
        return initiatingRequestID;
    }

    /**
     * Sets the value of the initiatingRequestID property.
     * 
     */
    public void setInitiatingRequestID(long value) {
        this.initiatingRequestID = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the objectionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectionCode() {
        return objectionCode;
    }

    /**
     * Sets the value of the objectionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectionCode(String value) {
        this.objectionCode = value;
    }

}
