//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Purpose - Network charge record type - "911" - Dispute Item 
 * 
 * &lt;p&gt;Java class for DisputeItem complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="DisputeItem"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="InvoiceNumber" type="{urn:aseXML:r38}InvoiceNumber"/&amp;gt;
 *         &amp;lt;element name="TransactionID" type="{urn:aseXML:r38}TransactionID"/&amp;gt;
 *         &amp;lt;element name="NMI" type="{urn:aseXML:r38}NMIWithChecksum"/&amp;gt;
 *         &amp;lt;element name="Charge" type="{urn:aseXML:r38}Amount" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="GST" type="{urn:aseXML:r38}GSTData" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="Code" type="{urn:aseXML:r38}DisputeReasonCode" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="Comment" type="{urn:aseXML:r38}SpecialComments" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="status" type="{urn:aseXML:r38}DisputeStatusCode" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisputeItem", propOrder = {
    "invoiceNumber",
    "transactionID",
    "nmi",
    "charge",
    "gst",
    "code",
    "comment"
})
public class DisputeItem {

    @XmlElement(name = "InvoiceNumber", required = true)
    protected String invoiceNumber;
    @XmlElement(name = "TransactionID", required = true)
    protected String transactionID;
    @XmlElement(name = "NMI", required = true)
    protected NMIWithChecksum nmi;
    @XmlElement(name = "Charge")
    protected BigDecimal charge;
    @XmlElement(name = "GST")
    protected GSTData gst;
    @XmlElement(name = "Code")
    @XmlSchemaType(name = "string")
    protected DisputeReasonCode code;
    @XmlElement(name = "Comment")
    protected SpecialComments comment;
    @XmlAttribute(name = "status")
    protected DisputeStatusCode status;

    /**
     * Gets the value of the invoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceNumber(String value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the transactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionID(String value) {
        this.transactionID = value;
    }

    /**
     * Gets the value of the nmi property.
     * 
     * @return
     *     possible object is
     *     {@link NMIWithChecksum }
     *     
     */
    public NMIWithChecksum getNMI() {
        return nmi;
    }

    /**
     * Sets the value of the nmi property.
     * 
     * @param value
     *     allowed object is
     *     {@link NMIWithChecksum }
     *     
     */
    public void setNMI(NMIWithChecksum value) {
        this.nmi = value;
    }

    /**
     * Gets the value of the charge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCharge() {
        return charge;
    }

    /**
     * Sets the value of the charge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCharge(BigDecimal value) {
        this.charge = value;
    }

    /**
     * Gets the value of the gst property.
     * 
     * @return
     *     possible object is
     *     {@link GSTData }
     *     
     */
    public GSTData getGST() {
        return gst;
    }

    /**
     * Sets the value of the gst property.
     * 
     * @param value
     *     allowed object is
     *     {@link GSTData }
     *     
     */
    public void setGST(GSTData value) {
        this.gst = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeReasonCode }
     *     
     */
    public DisputeReasonCode getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeReasonCode }
     *     
     */
    public void setCode(DisputeReasonCode value) {
        this.code = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialComments }
     *     
     */
    public SpecialComments getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialComments }
     *     
     */
    public void setComment(SpecialComments value) {
        this.comment = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeStatusCode }
     *     
     */
    public DisputeStatusCode getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeStatusCode }
     *     
     */
    public void setStatus(DisputeStatusCode value) {
        this.status = value;
    }

}
