//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Purpose - Network charge record type - "912" - Dispute Footer 
 * 
 * &lt;p&gt;Java class for DisputeFooter complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="DisputeFooter"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="RecordCount" type="{urn:aseXML:r38}RecordCount"/&amp;gt;
 *         &amp;lt;element name="TotalExclGST" type="{urn:aseXML:r38}Amount" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="TotalInclGST" type="{urn:aseXML:r38}Amount" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisputeFooter", propOrder = {
    "recordCount",
    "totalExclGST",
    "totalInclGST"
})
public class DisputeFooter {

    @XmlElement(name = "RecordCount", required = true)
    protected BigInteger recordCount;
    @XmlElement(name = "TotalExclGST")
    protected BigDecimal totalExclGST;
    @XmlElement(name = "TotalInclGST")
    protected BigDecimal totalInclGST;

    /**
     * Gets the value of the recordCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecordCount() {
        return recordCount;
    }

    /**
     * Sets the value of the recordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecordCount(BigInteger value) {
        this.recordCount = value;
    }

    /**
     * Gets the value of the totalExclGST property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalExclGST() {
        return totalExclGST;
    }

    /**
     * Sets the value of the totalExclGST property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalExclGST(BigDecimal value) {
        this.totalExclGST = value;
    }

    /**
     * Gets the value of the totalInclGST property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalInclGST() {
        return totalInclGST;
    }

    /**
     * Sets the value of the totalInclGST property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalInclGST(BigDecimal value) {
        this.totalInclGST = value;
    }

}
