//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * Application - To be used by an a Retailer to notify an LNSP of a fault where the FaultOutageAdvice was returned as "unknown", thus the Retailer has more information about a fault and must report it to the LNSP.
 * TransactionExchange - This tranaction would follow a FaultOutageAdvice if returned as unknown.
 * TransactionGroup - FLTS
 * Priority - High
 * Purpose - For a Retailer to notify an LNSP of a fault in the even that the Retailer has more information about the fault.
 * Detail -
 * 	  
 * 
 * &lt;p&gt;Java class for FaultNotification complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="FaultNotification"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="NMI" type="{urn:aseXML:r38}NMI" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="TimeOfCall" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&amp;gt;
 *         &amp;lt;element name="TimeOfOccurrence" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="FaultInformant" type="{urn:aseXML:r38}FaultInformant" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="FaultDescription" type="{urn:aseXML:r38}FaultDescription"/&amp;gt;
 *         &amp;lt;element name="CallBack" type="{urn:aseXML:r38}FaultCallBack" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="RetailerPriority" type="{urn:aseXML:r38}Priority" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="version" type="{urn:aseXML:r38}r14" default="r14" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FaultNotification", propOrder = {
    "nmi",
    "timeOfCall",
    "timeOfOccurrence",
    "faultInformant",
    "faultDescription",
    "callBack",
    "retailerPriority"
})
public class FaultNotification {

    @XmlElement(name = "NMI")
    protected NMI nmi;
    @XmlElement(name = "TimeOfCall", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeOfCall;
    @XmlElement(name = "TimeOfOccurrence")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeOfOccurrence;
    @XmlElement(name = "FaultInformant")
    protected FaultInformant faultInformant;
    @XmlElement(name = "FaultDescription", required = true)
    protected FaultDescription faultDescription;
    @XmlElement(name = "CallBack")
    protected FaultCallBack callBack;
    @XmlElement(name = "RetailerPriority")
    @XmlSchemaType(name = "string")
    protected Priority retailerPriority;
    @XmlAttribute(name = "version")
    protected R14 version;

    /**
     * Gets the value of the nmi property.
     * 
     * @return
     *     possible object is
     *     {@link NMI }
     *     
     */
    public NMI getNMI() {
        return nmi;
    }

    /**
     * Sets the value of the nmi property.
     * 
     * @param value
     *     allowed object is
     *     {@link NMI }
     *     
     */
    public void setNMI(NMI value) {
        this.nmi = value;
    }

    /**
     * Gets the value of the timeOfCall property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeOfCall() {
        return timeOfCall;
    }

    /**
     * Sets the value of the timeOfCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeOfCall(XMLGregorianCalendar value) {
        this.timeOfCall = value;
    }

    /**
     * Gets the value of the timeOfOccurrence property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeOfOccurrence() {
        return timeOfOccurrence;
    }

    /**
     * Sets the value of the timeOfOccurrence property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeOfOccurrence(XMLGregorianCalendar value) {
        this.timeOfOccurrence = value;
    }

    /**
     * Gets the value of the faultInformant property.
     * 
     * @return
     *     possible object is
     *     {@link FaultInformant }
     *     
     */
    public FaultInformant getFaultInformant() {
        return faultInformant;
    }

    /**
     * Sets the value of the faultInformant property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaultInformant }
     *     
     */
    public void setFaultInformant(FaultInformant value) {
        this.faultInformant = value;
    }

    /**
     * Gets the value of the faultDescription property.
     * 
     * @return
     *     possible object is
     *     {@link FaultDescription }
     *     
     */
    public FaultDescription getFaultDescription() {
        return faultDescription;
    }

    /**
     * Sets the value of the faultDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaultDescription }
     *     
     */
    public void setFaultDescription(FaultDescription value) {
        this.faultDescription = value;
    }

    /**
     * Gets the value of the callBack property.
     * 
     * @return
     *     possible object is
     *     {@link FaultCallBack }
     *     
     */
    public FaultCallBack getCallBack() {
        return callBack;
    }

    /**
     * Sets the value of the callBack property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaultCallBack }
     *     
     */
    public void setCallBack(FaultCallBack value) {
        this.callBack = value;
    }

    /**
     * Gets the value of the retailerPriority property.
     * 
     * @return
     *     possible object is
     *     {@link Priority }
     *     
     */
    public Priority getRetailerPriority() {
        return retailerPriority;
    }

    /**
     * Sets the value of the retailerPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Priority }
     *     
     */
    public void setRetailerPriority(Priority value) {
        this.retailerPriority = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R14 }
     *     
     */
    public R14 getVersion() {
        if (version == null) {
            return R14 .R_14;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R14 }
     *     
     */
    public void setVersion(R14 value) {
        this.version = value;
    }

}
