//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * &lt;p&gt;Java class for GasInformationResponseData complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="GasInformationResponseData"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{urn:aseXML:r38}WholesaleInformationResponseData"&amp;gt;
 *       &amp;lt;choice&amp;gt;
 *         &amp;lt;element name="CurrentMarketDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&amp;gt;
 *         &amp;lt;element name="MarketIntervalInfo" type="{urn:aseXML:r38}MarketIntervalInfoType"/&amp;gt;
 *       &amp;lt;/choice&amp;gt;
 *       &amp;lt;attribute name="version" type="{urn:aseXML:r38}r20" default="r20" /&amp;gt;
 *       &amp;lt;attribute name="contextType" use="required" type="{urn:aseXML:r38}GasInformationTransactionType" /&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GasInformationResponseData", propOrder = {
    "currentMarketDate",
    "marketIntervalInfo"
})
public class GasInformationResponseData
    extends WholesaleInformationResponseData
{

    @XmlElement(name = "CurrentMarketDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar currentMarketDate;
    @XmlElement(name = "MarketIntervalInfo")
    protected MarketIntervalInfoType marketIntervalInfo;
    @XmlAttribute(name = "version")
    protected R20 version;
    @XmlAttribute(name = "contextType", required = true)
    protected GasInformationTransactionType contextType;

    /**
     * Gets the value of the currentMarketDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCurrentMarketDate() {
        return currentMarketDate;
    }

    /**
     * Sets the value of the currentMarketDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCurrentMarketDate(XMLGregorianCalendar value) {
        this.currentMarketDate = value;
    }

    /**
     * Gets the value of the marketIntervalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MarketIntervalInfoType }
     *     
     */
    public MarketIntervalInfoType getMarketIntervalInfo() {
        return marketIntervalInfo;
    }

    /**
     * Sets the value of the marketIntervalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketIntervalInfoType }
     *     
     */
    public void setMarketIntervalInfo(MarketIntervalInfoType value) {
        this.marketIntervalInfo = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R20 }
     *     
     */
    public R20 getVersion() {
        if (version == null) {
            return R20 .R_20;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R20 }
     *     
     */
    public void setVersion(R20 value) {
        this.version = value;
    }

    /**
     * Gets the value of the contextType property.
     * 
     * @return
     *     possible object is
     *     {@link GasInformationTransactionType }
     *     
     */
    public GasInformationTransactionType getContextType() {
        return contextType;
    }

    /**
     * Sets the value of the contextType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasInformationTransactionType }
     *     
     */
    public void setContextType(GasInformationTransactionType value) {
        this.contextType = value;
    }

}
