//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Schema - Gas
 * 
 * &lt;p&gt;Java class for GasIntervalMeterStandingData complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="GasIntervalMeterStandingData"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="CommunicationEquipmentPresent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="ExcludedServicesCharges" minOccurs="0"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="ChargeItem" type="{urn:aseXML:r38}GasIntervalMeterCharge" maxOccurs="unbounded"/&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GasIntervalMeterStandingData", propOrder = {
    "communicationEquipmentPresent",
    "excludedServicesCharges"
})
public class GasIntervalMeterStandingData {

    @XmlElement(name = "CommunicationEquipmentPresent")
    protected Boolean communicationEquipmentPresent;
    @XmlElement(name = "ExcludedServicesCharges")
    protected GasIntervalMeterStandingData.ExcludedServicesCharges excludedServicesCharges;

    /**
     * Gets the value of the communicationEquipmentPresent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCommunicationEquipmentPresent() {
        return communicationEquipmentPresent;
    }

    /**
     * Sets the value of the communicationEquipmentPresent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCommunicationEquipmentPresent(Boolean value) {
        this.communicationEquipmentPresent = value;
    }

    /**
     * Gets the value of the excludedServicesCharges property.
     * 
     * @return
     *     possible object is
     *     {@link GasIntervalMeterStandingData.ExcludedServicesCharges }
     *     
     */
    public GasIntervalMeterStandingData.ExcludedServicesCharges getExcludedServicesCharges() {
        return excludedServicesCharges;
    }

    /**
     * Sets the value of the excludedServicesCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasIntervalMeterStandingData.ExcludedServicesCharges }
     *     
     */
    public void setExcludedServicesCharges(GasIntervalMeterStandingData.ExcludedServicesCharges value) {
        this.excludedServicesCharges = value;
    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="ChargeItem" type="{urn:aseXML:r38}GasIntervalMeterCharge" maxOccurs="unbounded"/&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "chargeItem"
    })
    public static class ExcludedServicesCharges {

        @XmlElement(name = "ChargeItem", required = true)
        protected List<GasIntervalMeterCharge> chargeItem;

        /**
         * Gets the value of the chargeItem property.
         * 
         * &lt;p&gt;
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the chargeItem property.
         * 
         * &lt;p&gt;
         * For example, to add a new item, do as follows:
         * &lt;pre&gt;
         *    getChargeItem().add(newItem);
         * &lt;/pre&gt;
         * 
         * 
         * &lt;p&gt;
         * Objects of the following type(s) are allowed in the list
         * {@link GasIntervalMeterCharge }
         * 
         * 
         */
        public List<GasIntervalMeterCharge> getChargeItem() {
            if (chargeItem == null) {
                chargeItem = new ArrayList<GasIntervalMeterCharge>();
            }
            return this.chargeItem;
        }

    }

}
