//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for GasMeterStatus.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="GasMeterStatus"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;enumeration value="No meter"/&amp;gt;
 *     &amp;lt;enumeration value="Turned on"/&amp;gt;
 *     &amp;lt;enumeration value="Turned off"/&amp;gt;
 *     &amp;lt;enumeration value="Plugged"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "GasMeterStatus")
@XmlEnum
public enum GasMeterStatus {

    @XmlEnumValue("No meter")
    NO_METER("No meter"),
    @XmlEnumValue("Turned on")
    TURNED_ON("Turned on"),
    @XmlEnumValue("Turned off")
    TURNED_OFF("Turned off"),
    @XmlEnumValue("Plugged")
    PLUGGED("Plugged");
    private final String value;

    GasMeterStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GasMeterStatus fromValue(String v) {
        for (GasMeterStatus c: GasMeterStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
