//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Schema - Gas
 * 
 * &lt;p&gt;Java class for GasServiceOrderDetails complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="GasServiceOrderDetails"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{urn:aseXML:r38}ServiceOrderRequestData"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="ServiceDetails" type="{urn:aseXML:r38}GasServiceDetails" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="DateTimeCSRAccessedRecord" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&amp;gt;
 *         &amp;lt;element name="DateTimeCSRProcessedTransaction" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&amp;gt;
 *         &amp;lt;element name="QuoteReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="ConnectionType" type="{urn:aseXML:r38}GasConnectionType" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="version" type="{urn:aseXML:r38}r36" default="r36" /&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GasServiceOrderDetails", propOrder = {
    "serviceDetails",
    "dateTimeCSRAccessedRecord",
    "dateTimeCSRProcessedTransaction",
    "quoteReference",
    "connectionType"
})
public class GasServiceOrderDetails
    extends ServiceOrderRequestData
{

    @XmlElement(name = "ServiceDetails")
    protected GasServiceDetails serviceDetails;
    @XmlElement(name = "DateTimeCSRAccessedRecord", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTimeCSRAccessedRecord;
    @XmlElement(name = "DateTimeCSRProcessedTransaction", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTimeCSRProcessedTransaction;
    @XmlElement(name = "QuoteReference")
    protected String quoteReference;
    @XmlElement(name = "ConnectionType")
    @XmlSchemaType(name = "string")
    protected GasConnectionType connectionType;
    @XmlAttribute(name = "version")
    protected R36 version;

    /**
     * Gets the value of the serviceDetails property.
     * 
     * @return
     *     possible object is
     *     {@link GasServiceDetails }
     *     
     */
    public GasServiceDetails getServiceDetails() {
        return serviceDetails;
    }

    /**
     * Sets the value of the serviceDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasServiceDetails }
     *     
     */
    public void setServiceDetails(GasServiceDetails value) {
        this.serviceDetails = value;
    }

    /**
     * Gets the value of the dateTimeCSRAccessedRecord property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTimeCSRAccessedRecord() {
        return dateTimeCSRAccessedRecord;
    }

    /**
     * Sets the value of the dateTimeCSRAccessedRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTimeCSRAccessedRecord(XMLGregorianCalendar value) {
        this.dateTimeCSRAccessedRecord = value;
    }

    /**
     * Gets the value of the dateTimeCSRProcessedTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTimeCSRProcessedTransaction() {
        return dateTimeCSRProcessedTransaction;
    }

    /**
     * Sets the value of the dateTimeCSRProcessedTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTimeCSRProcessedTransaction(XMLGregorianCalendar value) {
        this.dateTimeCSRProcessedTransaction = value;
    }

    /**
     * Gets the value of the quoteReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuoteReference() {
        return quoteReference;
    }

    /**
     * Sets the value of the quoteReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuoteReference(String value) {
        this.quoteReference = value;
    }

    /**
     * Gets the value of the connectionType property.
     * 
     * @return
     *     possible object is
     *     {@link GasConnectionType }
     *     
     */
    public GasConnectionType getConnectionType() {
        return connectionType;
    }

    /**
     * Sets the value of the connectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasConnectionType }
     *     
     */
    public void setConnectionType(GasConnectionType value) {
        this.connectionType = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R36 }
     *     
     */
    public R36 getVersion() {
        if (version == null) {
            return R36 .R_36;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R36 }
     *     
     */
    public void setVersion(R36 value) {
        this.version = value;
    }

}
