//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for IndexAdjustmentReasonCode.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="IndexAdjustmentReasonCode"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;enumeration value="Over Read"/&amp;gt;
 *     &amp;lt;enumeration value="Under Read"/&amp;gt;
 *     &amp;lt;enumeration value="Over Estimate"/&amp;gt;
 *     &amp;lt;enumeration value="Under Estimate"/&amp;gt;
 *     &amp;lt;enumeration value="No Change"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "IndexAdjustmentReasonCode")
@XmlEnum
public enum IndexAdjustmentReasonCode {

    @XmlEnumValue("Over Read")
    OVER_READ("Over Read"),
    @XmlEnumValue("Under Read")
    UNDER_READ("Under Read"),
    @XmlEnumValue("Over Estimate")
    OVER_ESTIMATE("Over Estimate"),
    @XmlEnumValue("Under Estimate")
    UNDER_ESTIMATE("Under Estimate"),
    @XmlEnumValue("No Change")
    NO_CHANGE("No Change");
    private final String value;

    IndexAdjustmentReasonCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IndexAdjustmentReasonCode fromValue(String v) {
        for (IndexAdjustmentReasonCode c: IndexAdjustmentReasonCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
