//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for LifeSupportEquipmentType.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="LifeSupportEquipmentType"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;enumeration value="Oxygen Concentrator"/&amp;gt;
 *     &amp;lt;enumeration value="Intermittent Peritoneal Dialysis Machine"/&amp;gt;
 *     &amp;lt;enumeration value="Kidney Dialysis Machine"/&amp;gt;
 *     &amp;lt;enumeration value="Chronic Positive Airways Pressure Respirator"/&amp;gt;
 *     &amp;lt;enumeration value="Crigler Najjar Syndrome Phototherapy Equipment"/&amp;gt;
 *     &amp;lt;enumeration value="Ventilator For Life Support"/&amp;gt;
 *     &amp;lt;enumeration value="Other"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "LifeSupportEquipmentType")
@XmlEnum
public enum LifeSupportEquipmentType {

    @XmlEnumValue("Oxygen Concentrator")
    OXYGEN_CONCENTRATOR("Oxygen Concentrator"),
    @XmlEnumValue("Intermittent Peritoneal Dialysis Machine")
    INTERMITTENT_PERITONEAL_DIALYSIS_MACHINE("Intermittent Peritoneal Dialysis Machine"),
    @XmlEnumValue("Kidney Dialysis Machine")
    KIDNEY_DIALYSIS_MACHINE("Kidney Dialysis Machine"),
    @XmlEnumValue("Chronic Positive Airways Pressure Respirator")
    CHRONIC_POSITIVE_AIRWAYS_PRESSURE_RESPIRATOR("Chronic Positive Airways Pressure Respirator"),
    @XmlEnumValue("Crigler Najjar Syndrome Phototherapy Equipment")
    CRIGLER_NAJJAR_SYNDROME_PHOTOTHERAPY_EQUIPMENT("Crigler Najjar Syndrome Phototherapy Equipment"),
    @XmlEnumValue("Ventilator For Life Support")
    VENTILATOR_FOR_LIFE_SUPPORT("Ventilator For Life Support"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    LifeSupportEquipmentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LifeSupportEquipmentType fromValue(String v) {
        for (LifeSupportEquipmentType c: LifeSupportEquipmentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
