//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Purpose - Parameters for requesting a Market Report. Provide the ReportID which will be the same for all chunks.
 * For example if chunk 6 is required out of a report sent as 10 chunks populate BeginBlockNumber and EndBlockNumber as 6
 * and TotalBlockNumber as 10.
 * 			
 * 
 * &lt;p&gt;Java class for MRMissingBlockParameters complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="MRMissingBlockParameters"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{urn:aseXML:r38}BaseReportParameters"&amp;gt;
 *       &amp;lt;choice&amp;gt;
 *         &amp;lt;element name="BlockParameters"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="ReportID" type="{urn:aseXML:r38}UniqueIdentifier"/&amp;gt;
 *                   &amp;lt;element name="BeginBlockNumber" type="{urn:aseXML:r38}ReplicationSequenceNumber"/&amp;gt;
 *                   &amp;lt;element name="EndBlockNumber" type="{urn:aseXML:r38}ReplicationSequenceNumber"/&amp;gt;
 *                   &amp;lt;element name="TotalBlockNumber" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="RecreateReport" type="{http://www.w3.org/2001/XMLSchema}boolean"/&amp;gt;
 *       &amp;lt;/choice&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MRMissingBlockParameters", propOrder = {
    "blockParameters",
    "recreateReport"
})
public class MRMissingBlockParameters
    extends BaseReportParameters
{

    @XmlElement(name = "BlockParameters")
    protected MRMissingBlockParameters.BlockParameters blockParameters;
    @XmlElement(name = "RecreateReport")
    protected Boolean recreateReport;

    /**
     * Gets the value of the blockParameters property.
     * 
     * @return
     *     possible object is
     *     {@link MRMissingBlockParameters.BlockParameters }
     *     
     */
    public MRMissingBlockParameters.BlockParameters getBlockParameters() {
        return blockParameters;
    }

    /**
     * Sets the value of the blockParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link MRMissingBlockParameters.BlockParameters }
     *     
     */
    public void setBlockParameters(MRMissingBlockParameters.BlockParameters value) {
        this.blockParameters = value;
    }

    /**
     * Gets the value of the recreateReport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRecreateReport() {
        return recreateReport;
    }

    /**
     * Sets the value of the recreateReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRecreateReport(Boolean value) {
        this.recreateReport = value;
    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="ReportID" type="{urn:aseXML:r38}UniqueIdentifier"/&amp;gt;
     *         &amp;lt;element name="BeginBlockNumber" type="{urn:aseXML:r38}ReplicationSequenceNumber"/&amp;gt;
     *         &amp;lt;element name="EndBlockNumber" type="{urn:aseXML:r38}ReplicationSequenceNumber"/&amp;gt;
     *         &amp;lt;element name="TotalBlockNumber" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reportID",
        "beginBlockNumber",
        "endBlockNumber",
        "totalBlockNumber"
    })
    public static class BlockParameters {

        @XmlElement(name = "ReportID", required = true)
        protected String reportID;
        @XmlElement(name = "BeginBlockNumber", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger beginBlockNumber;
        @XmlElement(name = "EndBlockNumber", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger endBlockNumber;
        @XmlElement(name = "TotalBlockNumber")
        protected Object totalBlockNumber;

        /**
         * Gets the value of the reportID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportID() {
            return reportID;
        }

        /**
         * Sets the value of the reportID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportID(String value) {
            this.reportID = value;
        }

        /**
         * Gets the value of the beginBlockNumber property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBeginBlockNumber() {
            return beginBlockNumber;
        }

        /**
         * Sets the value of the beginBlockNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBeginBlockNumber(BigInteger value) {
            this.beginBlockNumber = value;
        }

        /**
         * Gets the value of the endBlockNumber property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getEndBlockNumber() {
            return endBlockNumber;
        }

        /**
         * Sets the value of the endBlockNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setEndBlockNumber(BigInteger value) {
            this.endBlockNumber = value;
        }

        /**
         * Gets the value of the totalBlockNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getTotalBlockNumber() {
            return totalBlockNumber;
        }

        /**
         * Sets the value of the totalBlockNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setTotalBlockNumber(Object value) {
            this.totalBlockNumber = value;
        }

    }

}
