//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 	
 * 
 * &lt;p&gt;Java class for MultiMeterSiteAccessDetails complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="MultiMeterSiteAccessDetails"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{urn:aseXML:r38}NMIStandingData"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="MeterData" minOccurs="0"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="Meter" type="{urn:aseXML:r38}GasMultiMeterStandingDataType"/&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="SiteData" type="{urn:aseXML:r38}ServicePoint" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="Hazard" type="{urn:aseXML:r38}SiteHazard" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="LastModifiedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="version" type="{urn:aseXML:r38}r34" default="r34" /&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiMeterSiteAccessDetails", propOrder = {
    "meterData",
    "siteData",
    "hazard",
    "lastModifiedDateTime"
})
public class MultiMeterSiteAccessDetails
    extends NMIStandingData
{

    @XmlElement(name = "MeterData")
    protected MultiMeterSiteAccessDetails.MeterData meterData;
    @XmlElement(name = "SiteData")
    protected ServicePoint siteData;
    @XmlElement(name = "Hazard")
    protected List<SiteHazard> hazard;
    @XmlElement(name = "LastModifiedDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedDateTime;
    @XmlAttribute(name = "version")
    protected R34 version;

    /**
     * Gets the value of the meterData property.
     * 
     * @return
     *     possible object is
     *     {@link MultiMeterSiteAccessDetails.MeterData }
     *     
     */
    public MultiMeterSiteAccessDetails.MeterData getMeterData() {
        return meterData;
    }

    /**
     * Sets the value of the meterData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiMeterSiteAccessDetails.MeterData }
     *     
     */
    public void setMeterData(MultiMeterSiteAccessDetails.MeterData value) {
        this.meterData = value;
    }

    /**
     * Gets the value of the siteData property.
     * 
     * @return
     *     possible object is
     *     {@link ServicePoint }
     *     
     */
    public ServicePoint getSiteData() {
        return siteData;
    }

    /**
     * Sets the value of the siteData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicePoint }
     *     
     */
    public void setSiteData(ServicePoint value) {
        this.siteData = value;
    }

    /**
     * Gets the value of the hazard property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the hazard property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getHazard().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link SiteHazard }
     * 
     * 
     */
    public List<SiteHazard> getHazard() {
        if (hazard == null) {
            hazard = new ArrayList<SiteHazard>();
        }
        return this.hazard;
    }

    /**
     * Gets the value of the lastModifiedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedDateTime() {
        return lastModifiedDateTime;
    }

    /**
     * Sets the value of the lastModifiedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedDateTime(XMLGregorianCalendar value) {
        this.lastModifiedDateTime = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R34 }
     *     
     */
    public R34 getVersion() {
        if (version == null) {
            return R34 .R_34;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R34 }
     *     
     */
    public void setVersion(R34 value) {
        this.version = value;
    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="Meter" type="{urn:aseXML:r38}GasMultiMeterStandingDataType"/&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "meter"
    })
    public static class MeterData {

        @XmlElement(name = "Meter", required = true)
        protected GasMultiMeterStandingDataType meter;

        /**
         * Gets the value of the meter property.
         * 
         * @return
         *     possible object is
         *     {@link GasMultiMeterStandingDataType }
         *     
         */
        public GasMultiMeterStandingDataType getMeter() {
            return meter;
        }

        /**
         * Sets the value of the meter property.
         * 
         * @param value
         *     allowed object is
         *     {@link GasMultiMeterStandingDataType }
         *     
         */
        public void setMeter(GasMultiMeterStandingDataType value) {
            this.meter = value;
        }

    }

}
