//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Each Booking is made up of one or more Outages
 * 
 * &lt;p&gt;Java class for NOSOutageType complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="NOSOutageType"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="CompanyOutageId" type="{urn:aseXML:r38}CompanyOutageIdType"/&amp;gt;
 *         &amp;lt;element name="CompanyRefCode" minOccurs="0"&amp;gt;
 *           &amp;lt;simpleType&amp;gt;
 *             &amp;lt;restriction base="{urn:aseXML:r38}CompanyRefCodeType"&amp;gt;
 *             &amp;lt;/restriction&amp;gt;
 *           &amp;lt;/simpleType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="PlanStart" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="PlanFinish" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="ActualStart" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="ReasonVarPlanActualStart" type="{urn:aseXML:r38}EnumReasonVarPlanActualType" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="ActualFinish" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="ReasonVarPlanActualFinish" type="{urn:aseXML:r38}EnumReasonVarPlanActualType" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="DayRecallMin" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="NightRecallMin" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="DNSPAware" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="GenAware" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="OtherRegionAware" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="Notes" type="{urn:aseXML:r38}CompanyNotes" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="ResubmitReason" type="{urn:aseXML:r38}EnumResubmitReasonType" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="operationType" type="{urn:aseXML:r38}NOSOperationType" /&amp;gt;
 *       &amp;lt;attribute name="changedBy" type="{urn:aseXML:r38}MessageSecurityContext" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NOSOutageType", propOrder = {
    "companyOutageId",
    "companyRefCode",
    "planStart",
    "planFinish",
    "actualStart",
    "reasonVarPlanActualStart",
    "actualFinish",
    "reasonVarPlanActualFinish",
    "dayRecallMin",
    "nightRecallMin",
    "dnspAware",
    "genAware",
    "otherRegionAware",
    "notes",
    "resubmitReason"
})
public class NOSOutageType {

    @XmlElement(name = "CompanyOutageId", required = true)
    protected String companyOutageId;
    @XmlElement(name = "CompanyRefCode")
    protected String companyRefCode;
    @XmlElement(name = "PlanStart")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar planStart;
    @XmlElement(name = "PlanFinish")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar planFinish;
    @XmlElement(name = "ActualStart")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar actualStart;
    @XmlElement(name = "ReasonVarPlanActualStart")
    @XmlSchemaType(name = "string")
    protected EnumReasonVarPlanActualType reasonVarPlanActualStart;
    @XmlElement(name = "ActualFinish")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar actualFinish;
    @XmlElement(name = "ReasonVarPlanActualFinish")
    @XmlSchemaType(name = "string")
    protected EnumReasonVarPlanActualType reasonVarPlanActualFinish;
    @XmlElement(name = "DayRecallMin")
    protected Integer dayRecallMin;
    @XmlElement(name = "NightRecallMin")
    protected Integer nightRecallMin;
    @XmlElement(name = "DNSPAware", defaultValue = "false")
    protected Boolean dnspAware;
    @XmlElement(name = "GenAware", defaultValue = "false")
    protected Boolean genAware;
    @XmlElement(name = "OtherRegionAware", defaultValue = "false")
    protected Boolean otherRegionAware;
    @XmlElement(name = "Notes")
    protected CompanyNotes notes;
    @XmlElement(name = "ResubmitReason")
    @XmlSchemaType(name = "string")
    protected EnumResubmitReasonType resubmitReason;
    @XmlAttribute(name = "operationType")
    protected NOSOperationType operationType;
    @XmlAttribute(name = "changedBy")
    protected String changedBy;

    /**
     * Gets the value of the companyOutageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyOutageId() {
        return companyOutageId;
    }

    /**
     * Sets the value of the companyOutageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyOutageId(String value) {
        this.companyOutageId = value;
    }

    /**
     * Gets the value of the companyRefCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyRefCode() {
        return companyRefCode;
    }

    /**
     * Sets the value of the companyRefCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyRefCode(String value) {
        this.companyRefCode = value;
    }

    /**
     * Gets the value of the planStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPlanStart() {
        return planStart;
    }

    /**
     * Sets the value of the planStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPlanStart(XMLGregorianCalendar value) {
        this.planStart = value;
    }

    /**
     * Gets the value of the planFinish property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPlanFinish() {
        return planFinish;
    }

    /**
     * Sets the value of the planFinish property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPlanFinish(XMLGregorianCalendar value) {
        this.planFinish = value;
    }

    /**
     * Gets the value of the actualStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActualStart() {
        return actualStart;
    }

    /**
     * Sets the value of the actualStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActualStart(XMLGregorianCalendar value) {
        this.actualStart = value;
    }

    /**
     * Gets the value of the reasonVarPlanActualStart property.
     * 
     * @return
     *     possible object is
     *     {@link EnumReasonVarPlanActualType }
     *     
     */
    public EnumReasonVarPlanActualType getReasonVarPlanActualStart() {
        return reasonVarPlanActualStart;
    }

    /**
     * Sets the value of the reasonVarPlanActualStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumReasonVarPlanActualType }
     *     
     */
    public void setReasonVarPlanActualStart(EnumReasonVarPlanActualType value) {
        this.reasonVarPlanActualStart = value;
    }

    /**
     * Gets the value of the actualFinish property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActualFinish() {
        return actualFinish;
    }

    /**
     * Sets the value of the actualFinish property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActualFinish(XMLGregorianCalendar value) {
        this.actualFinish = value;
    }

    /**
     * Gets the value of the reasonVarPlanActualFinish property.
     * 
     * @return
     *     possible object is
     *     {@link EnumReasonVarPlanActualType }
     *     
     */
    public EnumReasonVarPlanActualType getReasonVarPlanActualFinish() {
        return reasonVarPlanActualFinish;
    }

    /**
     * Sets the value of the reasonVarPlanActualFinish property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumReasonVarPlanActualType }
     *     
     */
    public void setReasonVarPlanActualFinish(EnumReasonVarPlanActualType value) {
        this.reasonVarPlanActualFinish = value;
    }

    /**
     * Gets the value of the dayRecallMin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDayRecallMin() {
        return dayRecallMin;
    }

    /**
     * Sets the value of the dayRecallMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDayRecallMin(Integer value) {
        this.dayRecallMin = value;
    }

    /**
     * Gets the value of the nightRecallMin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNightRecallMin() {
        return nightRecallMin;
    }

    /**
     * Sets the value of the nightRecallMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNightRecallMin(Integer value) {
        this.nightRecallMin = value;
    }

    /**
     * Gets the value of the dnspAware property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDNSPAware() {
        return dnspAware;
    }

    /**
     * Sets the value of the dnspAware property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDNSPAware(Boolean value) {
        this.dnspAware = value;
    }

    /**
     * Gets the value of the genAware property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGenAware() {
        return genAware;
    }

    /**
     * Sets the value of the genAware property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGenAware(Boolean value) {
        this.genAware = value;
    }

    /**
     * Gets the value of the otherRegionAware property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOtherRegionAware() {
        return otherRegionAware;
    }

    /**
     * Sets the value of the otherRegionAware property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOtherRegionAware(Boolean value) {
        this.otherRegionAware = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyNotes }
     *     
     */
    public CompanyNotes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyNotes }
     *     
     */
    public void setNotes(CompanyNotes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the resubmitReason property.
     * 
     * @return
     *     possible object is
     *     {@link EnumResubmitReasonType }
     *     
     */
    public EnumResubmitReasonType getResubmitReason() {
        return resubmitReason;
    }

    /**
     * Sets the value of the resubmitReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumResubmitReasonType }
     *     
     */
    public void setResubmitReason(EnumResubmitReasonType value) {
        this.resubmitReason = value;
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link NOSOperationType }
     *     
     */
    public NOSOperationType getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NOSOperationType }
     *     
     */
    public void setOperationType(NOSOperationType value) {
        this.operationType = value;
    }

    /**
     * Gets the value of the changedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangedBy() {
        return changedBy;
    }

    /**
     * Sets the value of the changedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangedBy(String value) {
        this.changedBy = value;
    }

}
