//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for PTPDataExchange complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="PTPDataExchange"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="FreeFormData" type="{http://www.w3.org/2001/XMLSchema}anyType"/&amp;gt;
 *         &amp;lt;element name="AttachmentList" type="{urn:aseXML:r38}AttachmentList" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="version" type="{urn:aseXML:r38}r36" default="r36" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PTPDataExchange", propOrder = {
    "freeFormData",
    "attachmentList"
})
public class PTPDataExchange {

    @XmlElement(name = "FreeFormData", required = true, nillable = true)
    protected Object freeFormData;
    @XmlElement(name = "AttachmentList")
    protected AttachmentList attachmentList;
    @XmlAttribute(name = "version")
    protected R36 version;

    /**
     * Gets the value of the freeFormData property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFreeFormData() {
        return freeFormData;
    }

    /**
     * Sets the value of the freeFormData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFreeFormData(Object value) {
        this.freeFormData = value;
    }

    /**
     * Gets the value of the attachmentList property.
     * 
     * @return
     *     possible object is
     *     {@link AttachmentList }
     *     
     */
    public AttachmentList getAttachmentList() {
        return attachmentList;
    }

    /**
     * Sets the value of the attachmentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentList }
     *     
     */
    public void setAttachmentList(AttachmentList value) {
        this.attachmentList = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R36 }
     *     
     */
    public R36 getVersion() {
        if (version == null) {
            return R36 .R_36;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R36 }
     *     
     */
    public void setVersion(R36 value) {
        this.version = value;
    }

}
