//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Schema - Gas
 * 
 * &lt;p&gt;Java class for ServiceOrderGasNoAccessData complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="ServiceOrderGasNoAccessData"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;choice&amp;gt;
 *         &amp;lt;element name="SpecialReadNoAccess" type="{urn:aseXML:r38}GasSpecialReadNoAccess"/&amp;gt;
 *         &amp;lt;element name="DateOfAttemptedAccess" type="{http://www.w3.org/2001/XMLSchema}date"/&amp;gt;
 *       &amp;lt;/choice&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceOrderGasNoAccessData", propOrder = {
    "specialReadNoAccess",
    "dateOfAttemptedAccess"
})
public class ServiceOrderGasNoAccessData {

    @XmlElement(name = "SpecialReadNoAccess")
    protected GasSpecialReadNoAccess specialReadNoAccess;
    @XmlElement(name = "DateOfAttemptedAccess")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfAttemptedAccess;

    /**
     * Gets the value of the specialReadNoAccess property.
     * 
     * @return
     *     possible object is
     *     {@link GasSpecialReadNoAccess }
     *     
     */
    public GasSpecialReadNoAccess getSpecialReadNoAccess() {
        return specialReadNoAccess;
    }

    /**
     * Sets the value of the specialReadNoAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasSpecialReadNoAccess }
     *     
     */
    public void setSpecialReadNoAccess(GasSpecialReadNoAccess value) {
        this.specialReadNoAccess = value;
    }

    /**
     * Gets the value of the dateOfAttemptedAccess property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfAttemptedAccess() {
        return dateOfAttemptedAccess;
    }

    /**
     * Sets the value of the dateOfAttemptedAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfAttemptedAccess(XMLGregorianCalendar value) {
        this.dateOfAttemptedAccess = value;
    }

}
