//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Application - Meter Data Management
 * TransactionExchange - Settlement Data Delivery
 * TransactionGroup - MDMT
 * Priority - Low
 * Purpose - Provide settlement data
 * Detail - Only one type of settlement data can be delivered within a given transaction. 
 * 			
 * 
 * &lt;p&gt;Java class for SettlementDataNotification complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="SettlementDataNotification"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;choice&amp;gt;
 *         &amp;lt;element name="CSVAggregatedSettlementData" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 *         &amp;lt;element name="CSVNonAggregatedSettlementData" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 *       &amp;lt;/choice&amp;gt;
 *       &amp;lt;attribute name="version" type="{urn:aseXML:r38}r4" default="r4" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SettlementDataNotification", propOrder = {
    "csvAggregatedSettlementData",
    "csvNonAggregatedSettlementData"
})
public class SettlementDataNotification {

    @XmlElement(name = "CSVAggregatedSettlementData")
    protected String csvAggregatedSettlementData;
    @XmlElement(name = "CSVNonAggregatedSettlementData")
    protected String csvNonAggregatedSettlementData;
    @XmlAttribute(name = "version")
    protected R4 version;

    /**
     * Gets the value of the csvAggregatedSettlementData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSVAggregatedSettlementData() {
        return csvAggregatedSettlementData;
    }

    /**
     * Sets the value of the csvAggregatedSettlementData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSVAggregatedSettlementData(String value) {
        this.csvAggregatedSettlementData = value;
    }

    /**
     * Gets the value of the csvNonAggregatedSettlementData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSVNonAggregatedSettlementData() {
        return csvNonAggregatedSettlementData;
    }

    /**
     * Sets the value of the csvNonAggregatedSettlementData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSVNonAggregatedSettlementData(String value) {
        this.csvNonAggregatedSettlementData = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R4 }
     *     
     */
    public R4 getVersion() {
        if (version == null) {
            return R4 .R_4;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R4 }
     *     
     */
    public void setVersion(R4 value) {
        this.version = value;
    }

}
