//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package com.example.aemo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for SiteRequestReason.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="SiteRequestReason"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;maxLength value="40"/&amp;gt;
 *     &amp;lt;enumeration value="New Retailer for site"/&amp;gt;
 *     &amp;lt;enumeration value="Records old and need to be updated"/&amp;gt;
 *     &amp;lt;enumeration value="No Access details on file for NMI"/&amp;gt;
 *     &amp;lt;enumeration value="No Hazard Details on file for NMI"/&amp;gt;
 *     &amp;lt;enumeration value="Site Visit Required"/&amp;gt;
 *     &amp;lt;enumeration value="Other"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "SiteRequestReason")
@XmlEnum
public enum SiteRequestReason {

    @XmlEnumValue("New Retailer for site")
    NEW_RETAILER_FOR_SITE("New Retailer for site"),
    @XmlEnumValue("Records old and need to be updated")
    RECORDS_OLD_AND_NEED_TO_BE_UPDATED("Records old and need to be updated"),
    @XmlEnumValue("No Access details on file for NMI")
    NO_ACCESS_DETAILS_ON_FILE_FOR_NMI("No Access details on file for NMI"),
    @XmlEnumValue("No Hazard Details on file for NMI")
    NO_HAZARD_DETAILS_ON_FILE_FOR_NMI("No Hazard Details on file for NMI"),
    @XmlEnumValue("Site Visit Required")
    SITE_VISIT_REQUIRED("Site Visit Required"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    SiteRequestReason(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SiteRequestReason fromValue(String v) {
        for (SiteRequestReason c: SiteRequestReason.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
