//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Purpose - The payload used to carry acknowledgments
 * Detail - The aseXML acknowledgement model calls for each message and transaction to be acknowledged, subject to certain rules. For further information, refer to the aseXMl guidelines.
 * 
 * 
 * &lt;p&gt;Java class for Acknowledgements complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="Acknowledgements"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="MessageAcknowledgement" type="{urn:aseXML:r38}MessageAcknowledgement" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="TransactionAcknowledgement" type="{urn:aseXML:r38}TransactionAcknowledgement" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Acknowledgements", propOrder = {
    "messageAcknowledgement",
    "transactionAcknowledgement"
})
public class Acknowledgements {

    @XmlElement(name = "MessageAcknowledgement", namespace = "urn:aseXML:r38")
    protected List<MessageAcknowledgement> messageAcknowledgement;
    @XmlElement(name = "TransactionAcknowledgement")
    protected List<TransactionAcknowledgement> transactionAcknowledgement;

    /**
     * Gets the value of the messageAcknowledgement property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the messageAcknowledgement property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getMessageAcknowledgement().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link MessageAcknowledgement }
     * 
     * 
     */
    public List<MessageAcknowledgement> getMessageAcknowledgement() {
        if (messageAcknowledgement == null) {
            messageAcknowledgement = new ArrayList<MessageAcknowledgement>();
        }
        return this.messageAcknowledgement;
    }

    /**
     * Gets the value of the transactionAcknowledgement property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the transactionAcknowledgement property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getTransactionAcknowledgement().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link TransactionAcknowledgement }
     * 
     * 
     */
    public List<TransactionAcknowledgement> getTransactionAcknowledgement() {
        if (transactionAcknowledgement == null) {
            transactionAcknowledgement = new ArrayList<TransactionAcknowledgement>();
        }
        return this.transactionAcknowledgement;
    }

}
