//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for AustralianPostalDeliveryType.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="AustralianPostalDeliveryType"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;maxLength value="11"/&amp;gt;
 *     &amp;lt;enumeration value="CARE PO"/&amp;gt;
 *     &amp;lt;enumeration value="CMA"/&amp;gt;
 *     &amp;lt;enumeration value="CMB"/&amp;gt;
 *     &amp;lt;enumeration value="CPA"/&amp;gt;
 *     &amp;lt;enumeration value="GPO BOX"/&amp;gt;
 *     &amp;lt;enumeration value="LOCKED BAG"/&amp;gt;
 *     &amp;lt;enumeration value="MS"/&amp;gt;
 *     &amp;lt;enumeration value="PO BOX"/&amp;gt;
 *     &amp;lt;enumeration value="PRIVATE BAG"/&amp;gt;
 *     &amp;lt;enumeration value="RSD"/&amp;gt;
 *     &amp;lt;enumeration value="RMB"/&amp;gt;
 *     &amp;lt;enumeration value="RMS"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "AustralianPostalDeliveryType")
@XmlEnum
public enum AustralianPostalDeliveryType {

    @XmlEnumValue("CARE PO")
    CARE_PO("CARE PO"),
    CMA("CMA"),
    CMB("CMB"),
    CPA("CPA"),
    @XmlEnumValue("GPO BOX")
    GPO_BOX("GPO BOX"),
    @XmlEnumValue("LOCKED BAG")
    LOCKED_BAG("LOCKED BAG"),
    MS("MS"),
    @XmlEnumValue("PO BOX")
    PO_BOX("PO BOX"),
    @XmlEnumValue("PRIVATE BAG")
    PRIVATE_BAG("PRIVATE BAG"),
    RSD("RSD"),
    RMB("RMB"),
    RMS("RMS");
    private final String value;

    AustralianPostalDeliveryType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AustralianPostalDeliveryType fromValue(String v) {
        for (AustralianPostalDeliveryType c: AustralianPostalDeliveryType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
