//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * Purpose - Row of the CATSJurisdictionalRules table
 * MSATS Data Model Table - CATS_Jurisdictional_Rules
 * Replication Table Name - CATSJurisdictionalRules
 * 			
 * 
 * &lt;p&gt;Java class for CATSJurisdictionalRuleRow complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="CATSJurisdictionalRuleRow"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{urn:aseXML:r38}ReplicationDateRangeRow"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="ChangeReasonCode" type="{urn:aseXML:r38}CATSChangeReasonCode"/&amp;gt;
 *         &amp;lt;element name="JurisdictionCode" type="{urn:aseXML:r38}JurisdictionCode"/&amp;gt;
 *         &amp;lt;element name="ObjectionLodgementPeriod" type="{urn:aseXML:r38}CATSObjectionLodgementPeriod"/&amp;gt;
 *         &amp;lt;element name="ObjectionClearancePeriod" type="{urn:aseXML:r38}CATSObjectionClearancePeriod"/&amp;gt;
 *         &amp;lt;element name="NotificationPeriod" type="{urn:aseXML:r38}CATSNotificationPeriod"/&amp;gt;
 *         &amp;lt;element name="ProspectiveDays" type="{urn:aseXML:r38}CATSProspectiveDays"/&amp;gt;
 *         &amp;lt;element name="RetrospectiveDays" type="{urn:aseXML:r38}CATSRetrospectiveDays"/&amp;gt;
 *         &amp;lt;element name="TimeOfChange" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="NMIClassificationCode" type="{urn:aseXML:r38}NMIClassificationCode"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CATSJurisdictionalRuleRow", propOrder = {
    "changeReasonCode",
    "jurisdictionCode",
    "objectionLodgementPeriod",
    "objectionClearancePeriod",
    "notificationPeriod",
    "prospectiveDays",
    "retrospectiveDays",
    "timeOfChange",
    "nmiClassificationCode"
})
public class CATSJurisdictionalRuleRow
    extends ReplicationDateRangeRow
{

    @XmlElement(name = "ChangeReasonCode", required = true)
    protected String changeReasonCode;
    @XmlElement(name = "JurisdictionCode", required = true)
    protected String jurisdictionCode;
    @XmlElement(name = "ObjectionLodgementPeriod", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger objectionLodgementPeriod;
    @XmlElement(name = "ObjectionClearancePeriod", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger objectionClearancePeriod;
    @XmlElement(name = "NotificationPeriod", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger notificationPeriod;
    @XmlElement(name = "ProspectiveDays", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger prospectiveDays;
    @XmlElement(name = "RetrospectiveDays", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger retrospectiveDays;
    @XmlElementRef(name = "TimeOfChange", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> timeOfChange;
    @XmlElement(name = "NMIClassificationCode", required = true)
    protected String nmiClassificationCode;

    /**
     * Gets the value of the changeReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeReasonCode() {
        return changeReasonCode;
    }

    /**
     * Sets the value of the changeReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeReasonCode(String value) {
        this.changeReasonCode = value;
    }

    /**
     * Gets the value of the jurisdictionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJurisdictionCode() {
        return jurisdictionCode;
    }

    /**
     * Sets the value of the jurisdictionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJurisdictionCode(String value) {
        this.jurisdictionCode = value;
    }

    /**
     * Gets the value of the objectionLodgementPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObjectionLodgementPeriod() {
        return objectionLodgementPeriod;
    }

    /**
     * Sets the value of the objectionLodgementPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObjectionLodgementPeriod(BigInteger value) {
        this.objectionLodgementPeriod = value;
    }

    /**
     * Gets the value of the objectionClearancePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObjectionClearancePeriod() {
        return objectionClearancePeriod;
    }

    /**
     * Sets the value of the objectionClearancePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObjectionClearancePeriod(BigInteger value) {
        this.objectionClearancePeriod = value;
    }

    /**
     * Gets the value of the notificationPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNotificationPeriod() {
        return notificationPeriod;
    }

    /**
     * Sets the value of the notificationPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNotificationPeriod(BigInteger value) {
        this.notificationPeriod = value;
    }

    /**
     * Gets the value of the prospectiveDays property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProspectiveDays() {
        return prospectiveDays;
    }

    /**
     * Sets the value of the prospectiveDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProspectiveDays(BigInteger value) {
        this.prospectiveDays = value;
    }

    /**
     * Gets the value of the retrospectiveDays property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRetrospectiveDays() {
        return retrospectiveDays;
    }

    /**
     * Sets the value of the retrospectiveDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRetrospectiveDays(BigInteger value) {
        this.retrospectiveDays = value;
    }

    /**
     * Gets the value of the timeOfChange property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getTimeOfChange() {
        return timeOfChange;
    }

    /**
     * Sets the value of the timeOfChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setTimeOfChange(JAXBElement<XMLGregorianCalendar> value) {
        this.timeOfChange = value;
    }

    /**
     * Gets the value of the nmiClassificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNMIClassificationCode() {
        return nmiClassificationCode;
    }

    /**
     * Sets the value of the nmiClassificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNMIClassificationCode(String value) {
        this.nmiClassificationCode = value;
    }

}
