//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Purpose - Format for a CATS Participant System Status Report
 * Report Name - ParticipantSystemStatus
 * 			
 * 
 * &lt;p&gt;Java class for CATSParticipantSystemStatusReportFormat complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="CATSParticipantSystemStatusReportFormat"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{urn:aseXML:r38}BaseReportFormat"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="ParticipantSystemsStatus" type="{urn:aseXML:r38}ParticipantSystemsStatus"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CATSParticipantSystemStatusReportFormat", propOrder = {
    "participantSystemsStatus"
})
public class CATSParticipantSystemStatusReportFormat
    extends BaseReportFormat
{

    @XmlElement(name = "ParticipantSystemsStatus", required = true)
    protected ParticipantSystemsStatus participantSystemsStatus;

    /**
     * Gets the value of the participantSystemsStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ParticipantSystemsStatus }
     *     
     */
    public ParticipantSystemsStatus getParticipantSystemsStatus() {
        return participantSystemsStatus;
    }

    /**
     * Sets the value of the participantSystemsStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParticipantSystemsStatus }
     *     
     */
    public void setParticipantSystemsStatus(ParticipantSystemsStatus value) {
        this.participantSystemsStatus = value;
    }

}
