//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for CustomerCharacterisation.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="CustomerCharacterisation"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;enumeration value="Metropolitan Business"/&amp;gt;
 *     &amp;lt;enumeration value="Metropolitan Residential"/&amp;gt;
 *     &amp;lt;enumeration value="Non Metropolitan Business"/&amp;gt;
 *     &amp;lt;enumeration value="Non Metropolitan Residential"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "CustomerCharacterisation")
@XmlEnum
public enum CustomerCharacterisation {

    @XmlEnumValue("Metropolitan Business")
    METROPOLITAN_BUSINESS("Metropolitan Business"),
    @XmlEnumValue("Metropolitan Residential")
    METROPOLITAN_RESIDENTIAL("Metropolitan Residential"),
    @XmlEnumValue("Non Metropolitan Business")
    NON_METROPOLITAN_BUSINESS("Non Metropolitan Business"),
    @XmlEnumValue("Non Metropolitan Residential")
    NON_METROPOLITAN_RESIDENTIAL("Non Metropolitan Residential");
    private final String value;

    CustomerCharacterisation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CustomerCharacterisation fromValue(String v) {
        for (CustomerCharacterisation c: CustomerCharacterisation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
