//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for DisputeStatusData complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="DisputeStatusData"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="Header" type="{urn:aseXML:r38}NETBHeader"/&amp;gt;
 *         &amp;lt;element name="DisputeItems"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="DisputeItem" type="{urn:aseXML:r38}DisputeItem" maxOccurs="unbounded"/&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *         &amp;lt;element name="RecordCount" type="{urn:aseXML:r38}RecordCount"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisputeStatusData", propOrder = {
    "header",
    "disputeItems",
    "recordCount"
})
public class DisputeStatusData {

    @XmlElement(name = "Header", required = true)
    protected NETBHeader header;
    @XmlElement(name = "DisputeItems", required = true)
    protected DisputeStatusData.DisputeItems disputeItems;
    @XmlElement(name = "RecordCount", required = true)
    protected BigInteger recordCount;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link NETBHeader }
     *     
     */
    public NETBHeader getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link NETBHeader }
     *     
     */
    public void setHeader(NETBHeader value) {
        this.header = value;
    }

    /**
     * Gets the value of the disputeItems property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeStatusData.DisputeItems }
     *     
     */
    public DisputeStatusData.DisputeItems getDisputeItems() {
        return disputeItems;
    }

    /**
     * Sets the value of the disputeItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeStatusData.DisputeItems }
     *     
     */
    public void setDisputeItems(DisputeStatusData.DisputeItems value) {
        this.disputeItems = value;
    }

    /**
     * Gets the value of the recordCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecordCount() {
        return recordCount;
    }

    /**
     * Sets the value of the recordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecordCount(BigInteger value) {
        this.recordCount = value;
    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="DisputeItem" type="{urn:aseXML:r38}DisputeItem" maxOccurs="unbounded"/&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/restriction&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "disputeItem"
    })
    public static class DisputeItems {

        @XmlElement(name = "DisputeItem", required = true)
        protected List<DisputeItem> disputeItem;

        /**
         * Gets the value of the disputeItem property.
         * 
         * &lt;p&gt;
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the disputeItem property.
         * 
         * &lt;p&gt;
         * For example, to add a new item, do as follows:
         * &lt;pre&gt;
         *    getDisputeItem().add(newItem);
         * &lt;/pre&gt;
         * 
         * 
         * &lt;p&gt;
         * Objects of the following type(s) are allowed in the list
         * {@link DisputeItem }
         * 
         * 
         */
        public List<DisputeItem> getDisputeItem() {
            if (disputeItem == null) {
                disputeItem = new ArrayList<DisputeItem>();
            }
            return this.disputeItem;
        }

    }

}
