//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for ElectricityHSMDataInventoryResponseData complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="ElectricityHSMDataInventoryResponseData"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{urn:aseXML:r38}HSMDataInventoryResponseData"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="TriggeredEvents" type="{urn:aseXML:r38}HSMTriggeredEvents"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="version" type="{urn:aseXML:r38}r26" default="r26" /&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElectricityHSMDataInventoryResponseData", propOrder = {
    "triggeredEvents"
})
public class ElectricityHSMDataInventoryResponseData
    extends HSMDataInventoryResponseData
{

    @XmlElement(name = "TriggeredEvents", required = true, nillable = true)
    protected HSMTriggeredEvents triggeredEvents;
    @XmlAttribute(name = "version")
    protected R26 version;

    /**
     * Gets the value of the triggeredEvents property.
     * 
     * @return
     *     possible object is
     *     {@link HSMTriggeredEvents }
     *     
     */
    public HSMTriggeredEvents getTriggeredEvents() {
        return triggeredEvents;
    }

    /**
     * Sets the value of the triggeredEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link HSMTriggeredEvents }
     *     
     */
    public void setTriggeredEvents(HSMTriggeredEvents value) {
        this.triggeredEvents = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R26 }
     *     
     */
    public R26 getVersion() {
        if (version == null) {
            return R26 .R_26;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R26 }
     *     
     */
    public void setVersion(R26 value) {
        this.version = value;
    }

}
