//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for EnumCertaintyType.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="EnumCertaintyType"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;maxLength value="40"/&amp;gt;
 *     &amp;lt;whiteSpace value="collapse"/&amp;gt;
 *     &amp;lt;enumeration value="Scheduled"/&amp;gt;
 *     &amp;lt;enumeration value="Resourced"/&amp;gt;
 *     &amp;lt;enumeration value="Confirmed"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "EnumCertaintyType")
@XmlEnum
public enum EnumCertaintyType {

    @XmlEnumValue("Scheduled")
    SCHEDULED("Scheduled"),
    @XmlEnumValue("Resourced")
    RESOURCED("Resourced"),
    @XmlEnumValue("Confirmed")
    CONFIRMED("Confirmed");
    private final String value;

    EnumCertaintyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnumCertaintyType fromValue(String v) {
        for (EnumCertaintyType c: EnumCertaintyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
