//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Purpose - Envelope used by all aseXMLcompliant messages
 * Detail - The envelope consists of a header element followed by a payload element. The payload may either be one or more transactions, or one or more acknowledgements.
 * A detailed description of aseXML may be found in "Guidelines for Development of A Standard for Energy Transactions in XML (aseXML)".
 * 	
 * 
 * &lt;p&gt;Java class for Envelope complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="Envelope"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="Header" type="{urn:aseXML:r38}Header"/&amp;gt;
 *         &amp;lt;choice&amp;gt;
 *           &amp;lt;element name="Transactions" type="{urn:aseXML:r38}Transactions"/&amp;gt;
 *           &amp;lt;element name="Acknowledgements" type="{urn:aseXML:r38}Acknowledgements"/&amp;gt;
 *         &amp;lt;/choice&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Envelope", propOrder = {
    "header",
    "transactions",
    "acknowledgements"
})
public class Envelope {

    @XmlElement(name = "Header", required = true)
    protected Header header;
    @XmlElement(name = "Transactions")
    protected Transactions transactions;
    @XmlElement(name = "Acknowledgements")
    protected Acknowledgements acknowledgements;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the transactions property.
     * 
     * @return
     *     possible object is
     *     {@link Transactions }
     *     
     */
    public Transactions getTransactions() {
        return transactions;
    }

    /**
     * Sets the value of the transactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transactions }
     *     
     */
    public void setTransactions(Transactions value) {
        this.transactions = value;
    }

    /**
     * Gets the value of the acknowledgements property.
     * 
     * @return
     *     possible object is
     *     {@link Acknowledgements }
     *     
     */
    public Acknowledgements getAcknowledgements() {
        return acknowledgements;
    }

    /**
     * Sets the value of the acknowledgements property.
     * 
     * @param value
     *     allowed object is
     *     {@link Acknowledgements }
     *     
     */
    public void setAcknowledgements(Acknowledgements value) {
        this.acknowledgements = value;
    }

}
