//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Symptom/s of the fault
 * 
 * &lt;p&gt;Java class for FaultSymptoms complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="FaultSymptoms"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="Symptom" maxOccurs="4"&amp;gt;
 *           &amp;lt;simpleType&amp;gt;
 *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *               &amp;lt;enumeration value="ACR tripped"/&amp;gt;
 *               &amp;lt;enumeration value="Area street lights out"/&amp;gt;
 *               &amp;lt;enumeration value="Car hit pole"/&amp;gt;
 *               &amp;lt;enumeration value="Dim lights"/&amp;gt;
 *               &amp;lt;enumeration value="Damage to u/ground pillar"/&amp;gt;
 *               &amp;lt;enumeration value="Electric shock"/&amp;gt;
 *               &amp;lt;enumeration value="Explosion reports"/&amp;gt;
 *               &amp;lt;enumeration value="Fuse down"/&amp;gt;
 *               &amp;lt;enumeration value="Fire"/&amp;gt;
 *               &amp;lt;enumeration value="Glow reports"/&amp;gt;
 *               &amp;lt;enumeration value="High voltage injection"/&amp;gt;
 *               &amp;lt;enumeration value="Hot water 16h boost"/&amp;gt;
 *               &amp;lt;enumeration value="Intermittent supply"/&amp;gt;
 *               &amp;lt;enumeration value="Insufficient hot water"/&amp;gt;
 *               &amp;lt;enumeration value="Light/s out found by patrol"/&amp;gt;
 *               &amp;lt;enumeration value="Loss of supply - complete"/&amp;gt;
 *               &amp;lt;enumeration value="Loss of supply - partial"/&amp;gt;
 *               &amp;lt;enumeration value="Meter/timeswitch faulty"/&amp;gt;
 *               &amp;lt;enumeration value="No hot water"/&amp;gt;
 *               &amp;lt;enumeration value="Not listed"/&amp;gt;
 *               &amp;lt;enumeration value="Other"/&amp;gt;
 *               &amp;lt;enumeration value="Pole Down"/&amp;gt;
 *               &amp;lt;enumeration value="Pole Fire"/&amp;gt;
 *               &amp;lt;enumeration value="Urgent Public Hazard Report "/&amp;gt;
 *               &amp;lt;enumeration value="Urgent Public Hazard Report - fire"/&amp;gt;
 *               &amp;lt;enumeration value="Planned Outage"/&amp;gt;
 *               &amp;lt;enumeration value="Street lights out"/&amp;gt;
 *               &amp;lt;enumeration value="Sparks Reports"/&amp;gt;
 *               &amp;lt;enumeration value="Tree Near Wire"/&amp;gt;
 *               &amp;lt;enumeration value="Tree On Wire"/&amp;gt;
 *               &amp;lt;enumeration value="TV Interference"/&amp;gt;
 *               &amp;lt;enumeration value="Underground Cable"/&amp;gt;
 *               &amp;lt;enumeration value="Unknown"/&amp;gt;
 *               &amp;lt;enumeration value="Voltage complaints"/&amp;gt;
 *               &amp;lt;enumeration value="Wires down - pole to house"/&amp;gt;
 *               &amp;lt;enumeration value="Wires down - pole to pole"/&amp;gt;
 *               &amp;lt;enumeration value="Watchman Light Out"/&amp;gt;
 *               &amp;lt;enumeration value="Wildlife report"/&amp;gt;
 *             &amp;lt;/restriction&amp;gt;
 *           &amp;lt;/simpleType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FaultSymptoms", propOrder = {
    "symptom"
})
public class FaultSymptoms {

    @XmlElement(name = "Symptom", required = true)
    protected List<String> symptom;

    /**
     * Gets the value of the symptom property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the symptom property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getSymptom().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSymptom() {
        if (symptom == null) {
            symptom = new ArrayList<String>();
        }
        return this.symptom;
    }

}
