//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for GasANAMDQType complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="GasANAMDQType"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="NMI" type="{urn:aseXML:r38}NMI"/&amp;gt;
 *         &amp;lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}float"/&amp;gt;
 *         &amp;lt;element name="AMDQNominationGJ" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="CumulativeUsedAMDQPct" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="CumulativeUsedAMDQGJ" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GasANAMDQType", propOrder = {
    "nmi",
    "value",
    "amdqNominationGJ",
    "cumulativeUsedAMDQPct",
    "cumulativeUsedAMDQGJ"
})
public class GasANAMDQType {

    @XmlElement(name = "NMI", required = true)
    protected NMI nmi;
    @XmlElement(name = "Value")
    protected float value;
    @XmlElement(name = "AMDQNominationGJ")
    protected Float amdqNominationGJ;
    @XmlElementRef(name = "CumulativeUsedAMDQPct", type = JAXBElement.class, required = false)
    protected JAXBElement<Float> cumulativeUsedAMDQPct;
    @XmlElementRef(name = "CumulativeUsedAMDQGJ", type = JAXBElement.class, required = false)
    protected JAXBElement<Float> cumulativeUsedAMDQGJ;

    /**
     * Gets the value of the nmi property.
     * 
     * @return
     *     possible object is
     *     {@link NMI }
     *     
     */
    public NMI getNMI() {
        return nmi;
    }

    /**
     * Sets the value of the nmi property.
     * 
     * @param value
     *     allowed object is
     *     {@link NMI }
     *     
     */
    public void setNMI(NMI value) {
        this.nmi = value;
    }

    /**
     * Gets the value of the value property.
     * 
     */
    public float getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(float value) {
        this.value = value;
    }

    /**
     * Gets the value of the amdqNominationGJ property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAMDQNominationGJ() {
        return amdqNominationGJ;
    }

    /**
     * Sets the value of the amdqNominationGJ property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAMDQNominationGJ(Float value) {
        this.amdqNominationGJ = value;
    }

    /**
     * Gets the value of the cumulativeUsedAMDQPct property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Float }{@code >}
     *     
     */
    public JAXBElement<Float> getCumulativeUsedAMDQPct() {
        return cumulativeUsedAMDQPct;
    }

    /**
     * Sets the value of the cumulativeUsedAMDQPct property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Float }{@code >}
     *     
     */
    public void setCumulativeUsedAMDQPct(JAXBElement<Float> value) {
        this.cumulativeUsedAMDQPct = value;
    }

    /**
     * Gets the value of the cumulativeUsedAMDQGJ property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Float }{@code >}
     *     
     */
    public JAXBElement<Float> getCumulativeUsedAMDQGJ() {
        return cumulativeUsedAMDQGJ;
    }

    /**
     * Sets the value of the cumulativeUsedAMDQGJ property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Float }{@code >}
     *     
     */
    public void setCumulativeUsedAMDQGJ(JAXBElement<Float> value) {
        this.cumulativeUsedAMDQGJ = value;
    }

}
