//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for GasAgencyConfirmationType complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="GasAgencyConfirmationType"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="NominationId" type="{http://www.w3.org/2001/XMLSchema}long"/&amp;gt;
 *         &amp;lt;element name="CompanyId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="NominationStatus" type="{urn:aseXML:r38}GasNominationStatusType" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GasAgencyConfirmationType", propOrder = {
    "nominationId",
    "companyId",
    "nominationStatus"
})
public class GasAgencyConfirmationType {

    @XmlElement(name = "NominationId")
    protected long nominationId;
    @XmlElement(name = "CompanyId")
    protected Integer companyId;
    @XmlElement(name = "NominationStatus")
    @XmlSchemaType(name = "string")
    protected GasNominationStatusType nominationStatus;

    /**
     * Gets the value of the nominationId property.
     * 
     */
    public long getNominationId() {
        return nominationId;
    }

    /**
     * Sets the value of the nominationId property.
     * 
     */
    public void setNominationId(long value) {
        this.nominationId = value;
    }

    /**
     * Gets the value of the companyId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * Sets the value of the companyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCompanyId(Integer value) {
        this.companyId = value;
    }

    /**
     * Gets the value of the nominationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link GasNominationStatusType }
     *     
     */
    public GasNominationStatusType getNominationStatus() {
        return nominationStatus;
    }

    /**
     * Sets the value of the nominationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasNominationStatusType }
     *     
     */
    public void setNominationStatus(GasNominationStatusType value) {
        this.nominationStatus = value;
    }

}
