//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for GasIHNAMDQType complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="GasIHNAMDQType"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="CloseProximityPoint" type="{urn:aseXML:r38}NMI"/&amp;gt;
 *         &amp;lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GasIHNAMDQType", propOrder = {
    "closeProximityPoint",
    "quantity"
})
public class GasIHNAMDQType {

    @XmlElement(name = "CloseProximityPoint", required = true)
    protected NMI closeProximityPoint;
    @XmlElement(name = "Quantity")
    protected int quantity;

    /**
     * Gets the value of the closeProximityPoint property.
     * 
     * @return
     *     possible object is
     *     {@link NMI }
     *     
     */
    public NMI getCloseProximityPoint() {
        return closeProximityPoint;
    }

    /**
     * Sets the value of the closeProximityPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link NMI }
     *     
     */
    public void setCloseProximityPoint(NMI value) {
        this.closeProximityPoint = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(int value) {
        this.quantity = value;
    }

}
