//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Schema - MeterDataManagement
 * 
 * &lt;p&gt;Java class for GasSingleHistoryRequestData complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="GasSingleHistoryRequestData"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{urn:aseXML:r38}NMITransactionBase"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="RequestPeriod" type="{urn:aseXML:r38}Period"/&amp;gt;
 *         &amp;lt;element name="FullHistoryRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="version" type="{urn:aseXML:r38}r9" default="r9" /&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GasSingleHistoryRequestData", propOrder = {
    "requestPeriod",
    "fullHistoryRequired"
})
public class GasSingleHistoryRequestData
    extends NMITransactionBase
{

    @XmlElement(name = "RequestPeriod", required = true)
    protected Period requestPeriod;
    @XmlElement(name = "FullHistoryRequired")
    protected boolean fullHistoryRequired;
    @XmlAttribute(name = "version")
    protected R9 version;

    /**
     * Gets the value of the requestPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getRequestPeriod() {
        return requestPeriod;
    }

    /**
     * Sets the value of the requestPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setRequestPeriod(Period value) {
        this.requestPeriod = value;
    }

    /**
     * Gets the value of the fullHistoryRequired property.
     * 
     */
    public boolean isFullHistoryRequired() {
        return fullHistoryRequired;
    }

    /**
     * Sets the value of the fullHistoryRequired property.
     * 
     */
    public void setFullHistoryRequired(boolean value) {
        this.fullHistoryRequired = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R9 }
     *     
     */
    public R9 getVersion() {
        if (version == null) {
            return R9 .R_9;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R9 }
     *     
     */
    public void setVersion(R9 value) {
        this.version = value;
    }

}
