//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for GasServiceOrderType complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="GasServiceOrderType"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{urn:aseXML:r38}ServiceOrderTypeBase"&amp;gt;
 *       &amp;lt;choice&amp;gt;
 *         &amp;lt;element name="JobEnquiryCode" type="{urn:aseXML:r38}JobEnquiryCode"/&amp;gt;
 *         &amp;lt;sequence&amp;gt;
 *           &amp;lt;element name="SpecialReadReasonCode" type="{urn:aseXML:r38}SpecialReadReasonCode"/&amp;gt;
 *           &amp;lt;element name="MeterSerialNumber" type="{urn:aseXML:r38}MeterSerialNumber" minOccurs="0"/&amp;gt;
 *         &amp;lt;/sequence&amp;gt;
 *       &amp;lt;/choice&amp;gt;
 *       &amp;lt;attribute name="version" type="{urn:aseXML:r38}r13" default="r13" /&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GasServiceOrderType", propOrder = {
    "jobEnquiryCode",
    "specialReadReasonCode",
    "meterSerialNumber"
})
public class GasServiceOrderType
    extends ServiceOrderTypeBase
{

    @XmlElement(name = "JobEnquiryCode")
    @XmlSchemaType(name = "string")
    protected JobEnquiryCode jobEnquiryCode;
    @XmlElement(name = "SpecialReadReasonCode")
    @XmlSchemaType(name = "string")
    protected SpecialReadReasonCode specialReadReasonCode;
    @XmlElement(name = "MeterSerialNumber")
    protected String meterSerialNumber;
    @XmlAttribute(name = "version")
    protected R13 version;

    /**
     * Gets the value of the jobEnquiryCode property.
     * 
     * @return
     *     possible object is
     *     {@link JobEnquiryCode }
     *     
     */
    public JobEnquiryCode getJobEnquiryCode() {
        return jobEnquiryCode;
    }

    /**
     * Sets the value of the jobEnquiryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobEnquiryCode }
     *     
     */
    public void setJobEnquiryCode(JobEnquiryCode value) {
        this.jobEnquiryCode = value;
    }

    /**
     * Gets the value of the specialReadReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialReadReasonCode }
     *     
     */
    public SpecialReadReasonCode getSpecialReadReasonCode() {
        return specialReadReasonCode;
    }

    /**
     * Sets the value of the specialReadReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialReadReasonCode }
     *     
     */
    public void setSpecialReadReasonCode(SpecialReadReasonCode value) {
        this.specialReadReasonCode = value;
    }

    /**
     * Gets the value of the meterSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeterSerialNumber() {
        return meterSerialNumber;
    }

    /**
     * Sets the value of the meterSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeterSerialNumber(String value) {
        this.meterSerialNumber = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R13 }
     *     
     */
    public R13 getVersion() {
        if (version == null) {
            return R13 .R_13;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R13 }
     *     
     */
    public void setVersion(R13 value) {
        this.version = value;
    }

}
