//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for NoticeOfMeteringWorks complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="NoticeOfMeteringWorks"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="NoticeOfWorksID" type="{urn:aseXML:r38}NoticeOfWorksID"/&amp;gt;
 *         &amp;lt;element name="NMIStandingData" type="{urn:aseXML:r38}NMIStandingData"/&amp;gt;
 *         &amp;lt;element name="GeographicCoordinate" type="{urn:aseXML:r38}GeographicCoordinate" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="MeterWorksDetail" type="{urn:aseXML:r38}WorksDetail"/&amp;gt;
 *         &amp;lt;element name="Notes" type="{urn:aseXML:r38}NotificationNotes" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="version" type="{urn:aseXML:r38}r36" default="r36" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NoticeOfMeteringWorks", propOrder = {
    "noticeOfWorksID",
    "nmiStandingData",
    "geographicCoordinate",
    "meterWorksDetail",
    "notes"
})
public class NoticeOfMeteringWorks {

    @XmlElement(name = "NoticeOfWorksID", required = true)
    protected String noticeOfWorksID;
    @XmlElement(name = "NMIStandingData", required = true)
    protected NMIStandingData nmiStandingData;
    @XmlElement(name = "GeographicCoordinate")
    protected GeographicCoordinate geographicCoordinate;
    @XmlElement(name = "MeterWorksDetail", required = true)
    protected WorksDetail meterWorksDetail;
    @XmlElement(name = "Notes")
    protected String notes;
    @XmlAttribute(name = "version")
    protected R36 version;

    /**
     * Gets the value of the noticeOfWorksID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoticeOfWorksID() {
        return noticeOfWorksID;
    }

    /**
     * Sets the value of the noticeOfWorksID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoticeOfWorksID(String value) {
        this.noticeOfWorksID = value;
    }

    /**
     * Gets the value of the nmiStandingData property.
     * 
     * @return
     *     possible object is
     *     {@link NMIStandingData }
     *     
     */
    public NMIStandingData getNMIStandingData() {
        return nmiStandingData;
    }

    /**
     * Sets the value of the nmiStandingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link NMIStandingData }
     *     
     */
    public void setNMIStandingData(NMIStandingData value) {
        this.nmiStandingData = value;
    }

    /**
     * Gets the value of the geographicCoordinate property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicCoordinate }
     *     
     */
    public GeographicCoordinate getGeographicCoordinate() {
        return geographicCoordinate;
    }

    /**
     * Sets the value of the geographicCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicCoordinate }
     *     
     */
    public void setGeographicCoordinate(GeographicCoordinate value) {
        this.geographicCoordinate = value;
    }

    /**
     * Gets the value of the meterWorksDetail property.
     * 
     * @return
     *     possible object is
     *     {@link WorksDetail }
     *     
     */
    public WorksDetail getMeterWorksDetail() {
        return meterWorksDetail;
    }

    /**
     * Sets the value of the meterWorksDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorksDetail }
     *     
     */
    public void setMeterWorksDetail(WorksDetail value) {
        this.meterWorksDetail = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R36 }
     *     
     */
    public R36 getVersion() {
        if (version == null) {
            return R36 .R_36;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R36 }
     *     
     */
    public void setVersion(R36 value) {
        this.version = value;
    }

}
