//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Application - Table Replication
 * TransactionExchange - Replication Request
 * TransactionGroup - Multiple
 * Priority - Low
 * Purpose - Request a portion of a table
 * Detail - Large amounts of data may need to be transferred via table replication. In order that these requests do not adversely affect system performance, a limit is placed on how many rows may be retrieved by any one request. To "step through" the data required, an initial transaction with a LastSequenceNumber of zero should be used. The logic of the transaction handler should always sort by sequence number and request rows greater than that provided by the LastSequenceNumber element. Subsequent requests should use the largest sequence number seen in the previous response transaction. For efficiency, the data in ReplicationNotifications should be sorted in assending sequence number allowing the sequence number on the last row of the previous response transaction to be used.
 * 
 * The date range provided on the request allows finer grained control over the data provided, and supports a incremental download from a previously established baseline. To obtain all data, use a CreationFromDate  of 2001-01-01T00:00:00+00:00 and a CreationToDate of 9999-12-31T23:59:59+00:00.
 * 			
 * 
 * &lt;p&gt;Java class for ReplicationRequest complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="ReplicationRequest"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="ReplicationParameters" type="{urn:aseXML:r38}ReplicationParameters"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="version" type="{urn:aseXML:r38}r10" default="r10" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReplicationRequest", propOrder = {
    "replicationParameters"
})
public class ReplicationRequest {

    @XmlElement(name = "ReplicationParameters", required = true)
    protected ReplicationParameters replicationParameters;
    @XmlAttribute(name = "version")
    protected R10 version;

    /**
     * Gets the value of the replicationParameters property.
     * 
     * @return
     *     possible object is
     *     {@link ReplicationParameters }
     *     
     */
    public ReplicationParameters getReplicationParameters() {
        return replicationParameters;
    }

    /**
     * Sets the value of the replicationParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplicationParameters }
     *     
     */
    public void setReplicationParameters(ReplicationParameters value) {
        this.replicationParameters = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R10 }
     *     
     */
    public R10 getVersion() {
        if (version == null) {
            return R10 .R_10;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R10 }
     *     
     */
    public void setVersion(R10 value) {
        this.version = value;
    }

}
