//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Schema - Gas
 * 
 * &lt;p&gt;Java class for ServiceOrderGasMeterData complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="ServiceOrderGasMeterData"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{urn:aseXML:r38}BaseServiceOrderGasMeterData"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;choice&amp;gt;
 *           &amp;lt;sequence&amp;gt;
 *             &amp;lt;element name="New" type="{urn:aseXML:r38}GasMeterStandingData" minOccurs="0"/&amp;gt;
 *             &amp;lt;element name="Removed" type="{urn:aseXML:r38}GasMeterStandingData" minOccurs="0"/&amp;gt;
 *           &amp;lt;/sequence&amp;gt;
 *           &amp;lt;element name="Current" type="{urn:aseXML:r38}GasMeterStandingData"/&amp;gt;
 *         &amp;lt;/choice&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceOrderGasMeterData", propOrder = {
    "_new",
    "removed",
    "current"
})
public class ServiceOrderGasMeterData
    extends BaseServiceOrderGasMeterData
{

    @XmlElement(name = "New")
    protected GasMeterStandingData _new;
    @XmlElement(name = "Removed")
    protected GasMeterStandingData removed;
    @XmlElement(name = "Current")
    protected GasMeterStandingData current;

    /**
     * Gets the value of the new property.
     * 
     * @return
     *     possible object is
     *     {@link GasMeterStandingData }
     *     
     */
    public GasMeterStandingData getNew() {
        return _new;
    }

    /**
     * Sets the value of the new property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasMeterStandingData }
     *     
     */
    public void setNew(GasMeterStandingData value) {
        this._new = value;
    }

    /**
     * Gets the value of the removed property.
     * 
     * @return
     *     possible object is
     *     {@link GasMeterStandingData }
     *     
     */
    public GasMeterStandingData getRemoved() {
        return removed;
    }

    /**
     * Sets the value of the removed property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasMeterStandingData }
     *     
     */
    public void setRemoved(GasMeterStandingData value) {
        this.removed = value;
    }

    /**
     * Gets the value of the current property.
     * 
     * @return
     *     possible object is
     *     {@link GasMeterStandingData }
     *     
     */
    public GasMeterStandingData getCurrent() {
        return current;
    }

    /**
     * Sets the value of the current property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasMeterStandingData }
     *     
     */
    public void setCurrent(GasMeterStandingData value) {
        this.current = value;
    }

}
