//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Schema - ServiceOrder
 * 
 * &lt;p&gt;Java class for ServiceOrderHeader complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="ServiceOrderHeader"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;choice&amp;gt;
 *           &amp;lt;element name="NMI" type="{urn:aseXML:r38}NMI"/&amp;gt;
 *           &amp;lt;element name="Address" type="{urn:aseXML:r38}Address"/&amp;gt;
 *         &amp;lt;/choice&amp;gt;
 *         &amp;lt;element name="ServiceOrderType" type="{urn:aseXML:r38}ServiceOrderTypeBase" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="ServiceOrderNumber" type="{urn:aseXML:r38}UniqueIdentifier" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="ServiceProviderReference" type="{urn:aseXML:r38}UniqueIdentifier" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceOrderHeader", propOrder = {
    "nmi",
    "address",
    "serviceOrderType",
    "serviceOrderNumber",
    "serviceProviderReference"
})
public class ServiceOrderHeader {

    @XmlElement(name = "NMI")
    protected NMI nmi;
    @XmlElement(name = "Address")
    protected Address address;
    @XmlElement(name = "ServiceOrderType")
    protected ServiceOrderTypeBase serviceOrderType;
    @XmlElement(name = "ServiceOrderNumber")
    protected String serviceOrderNumber;
    @XmlElement(name = "ServiceProviderReference")
    protected String serviceProviderReference;

    /**
     * Gets the value of the nmi property.
     * 
     * @return
     *     possible object is
     *     {@link NMI }
     *     
     */
    public NMI getNMI() {
        return nmi;
    }

    /**
     * Sets the value of the nmi property.
     * 
     * @param value
     *     allowed object is
     *     {@link NMI }
     *     
     */
    public void setNMI(NMI value) {
        this.nmi = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the serviceOrderType property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceOrderTypeBase }
     *     
     */
    public ServiceOrderTypeBase getServiceOrderType() {
        return serviceOrderType;
    }

    /**
     * Sets the value of the serviceOrderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceOrderTypeBase }
     *     
     */
    public void setServiceOrderType(ServiceOrderTypeBase value) {
        this.serviceOrderType = value;
    }

    /**
     * Gets the value of the serviceOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceOrderNumber() {
        return serviceOrderNumber;
    }

    /**
     * Sets the value of the serviceOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceOrderNumber(String value) {
        this.serviceOrderNumber = value;
    }

    /**
     * Gets the value of the serviceProviderReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceProviderReference() {
        return serviceProviderReference;
    }

    /**
     * Sets the value of the serviceProviderReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceProviderReference(String value) {
        this.serviceProviderReference = value;
    }

}
