//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 12:34:41 PM AEST 
//


package aemo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for UserProfieType.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="UserProfieType"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;enumeration value="UPF"/&amp;gt;
 *     &amp;lt;enumeration value="UBPF"/&amp;gt;
 *     &amp;lt;enumeration value="UIPF"/&amp;gt;
 *     &amp;lt;enumeration value="RPF"/&amp;gt;
 *     &amp;lt;enumeration value="SPF"/&amp;gt;
 *     &amp;lt;enumeration value="UUAFGPF"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "UserProfieType")
@XmlEnum
public enum UserProfieType {

    UPF,
    UBPF,
    UIPF,
    RPF,
    SPF,
    UUAFGPF;

    public String value() {
        return name();
    }

    public static UserProfieType fromValue(String v) {
        return valueOf(v);
    }

}
